### ISSUE TITLE
LaunchWrapper

### ISSUE THREAD

**Issue by laci200270** [tomsik68/mclauncher-api#12]
Please modify the api to use laucnhwrapper(for forge)

**Comment by tomsik68** [comment]
In the latest commit(b737e967c03f77c1bd9304824d264f2315284ff3), I've added lots of possibilities for mods, which should hopefully help you to get forge running. Please take a look at it...

**Comment by laci200270** [comment]
For forge libray files i founded a solution: in the multimc launcher a "patch" json file patches the vannila version file.If you can implemtent add this feature to mcdownloadlauncher(pack.json file for example in the ftb)

**Comment by laci200270** [comment]
Or simply add version option to replace version file(in the installing)

**Comment by laci200270** [comment]
Can you do this?

**Comment by laci200270** [comment]
It works now :+1:
