### ISSUE TITLE
wrong usage of ETag/If-None-Match

### ISSUE THREAD

**Issue by leozzyzheng** [tomsik68/mclauncher-api#14]
In FileUtils.java function downloadFileWithProgress

        URLConnection connection = u.openConnection();
        if (md5 != null)
            connection.setRequestProperty("If-None-Match", md5);
        connection.connect();

The correct usage should be

        URLConnection connection = u.openConnection();
        if (md5 != null)
            connection.setRequestProperty("If-None-Match", "\"" + md5 + "\"");
        connection.connect();

**Comment by leozzyzheng** [comment]
And also , using HttpURLConnection allow you to check the ResponseCode is 304 or not to decide the whether you should use the local file.

**Comment by tomsik68** [comment]
If I surround the MD5 with quotes, behavior stays the same. Are you sure the change is required? 

Also, ETag and If-None-Match are 2 different things. If-None-Match is set by client to tell server "I've got this file. Is there an updated version?". Server responds with 304 if client file is up-to-date. If-None-Match is not surrounded by quotes even in vanilla mc launcher.

ETag is set by server. After downloading the file, client can calculate its MD5 digest to make sure it's correctly downloaded. If MD5s don't match, client will re-initiate the download. ETag may be enclosed in quotes.

**Comment by leozzyzheng** [comment]
I know how If-None-Match and ETag works.
I'm using the unquoted code in my project and it always return the quoted ETag with 200 not 304. After I add the quotes , the server now return 304 let me know they are the same file.
Your code in github ------

        URL u = new URL(url);
        HttpURLConnection connection = (HttpURLConnection)u.openConnection();
        if (md5 != null)
            connection.setRequestProperty("If-None-Match", md5);
        connection.connect();

        // local copy is up-to-date
        if(connection.getResponseCode() == 304){
            return;
        }
        createFileSafely(dest);

        BufferedInputStream in = new BufferedInputStream(connection.getInputStream());
        BufferedOutputStream out = new BufferedOutputStream(new FileOutputStream(dest));

        final int len = connection.getContentLength();
        if (progress != null)
            progress.setMax(len);

        int readBytes = 0;
        byte[] block;

        while (readBytes < len) {
            block = new byte[8192];
            int readNow = in.read(block);
            if (readNow > 0)
                out.write(block, 0, readNow);
            if (progress != null)
                progress.setProgress(readBytes);
            readBytes += readNow;
        }
        out.flush();
        out.close();
        in.close();

It does check the http code , so you can check whether the code is 200 or 304. It always return 200 even the md5 is the same.

**Comment by leozzyzheng** [comment]
According to http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.26
If-None-Match should be `( "*" | 1#entity-tag )`. So If `ETag` is be enclosed in quotes , If-None-Match also should use quotes.
The rfc2616 only say `Comparison of expectation values is case-insensitive for unquoted tokens (including the 100-continue token), and is case-sensitive for quoted-string expectation-extensions.` for  ETag. 

So it is my mistake , it means the server of minecraft didn't allow case-insensitive usage.
