### ISSUE TITLE
[Help] Launcher With Forge

### ISSUE THREAD

**Issue by mcNETDev** [tomsik68/mclauncher-api#15]
Hey can you give an template how i can launch Minecraft with this api with Forge ?

https://github.com/tomsik68/mclauncher-api/blob/master/src/test/java/TestMCDownloadForgeLaunch.java

this is not up to date or ?

-----------
mcNETDev

**Comment by laci200270** [comment]
what now works?

**Comment by mcNETDev** [comment]
The BasicModdingProfile Don't exist...

**Comment by mcNETDev** [comment]
@laci200270 How i can launch with minecraft Forge?

**Comment by laci200270** [comment]
I'm now not close to my IDE but maybe try launch with launchwrapper and add tweka class fmltweaker

**Comment by mcNETDev** [comment]
okay

**Comment by tomsik68** [comment]
@mcNETDev 
Yes, TestMCDownloadForgeLaunch is not up to date. API is not yet 100% compatible with forge, but it should be possible to run it. As far as I know, you need to create your own IModdingProfile implementation, add forge JAR to be injected before libraries and change the main class to launchwrapper class(I don't know the exact name, but if you install forge with official installer, you should find it in the JSON file in versions/1.7.9-Forge-34897/1.7.9-Forge-34897.json etc).

**Comment by mcNETDev** [comment]
@tomsik68 okay I've got it I can start just forge and now I get the error in the console


[21:49:04] [main/ERROR] [FML]: There is a binary discrepency between the expected input class sn (sn) and the actual class. Checksum on disk is 7d1bf79f, in patch b9c3ef9a. Things are probably about to go very wrong. Did you put something into the jar file?
[21:49:04] [main/ERROR] [FML]: The game is going to exit, because this is a critical error, and it is very improbable that the modded game will work, please obtain clean jar files.


here is the full log http://pastebin.com/WicQMuZc
Tomorrow I will continue i am from germany and it is bedtime ;)

**Comment by tomsik68** [comment]
I've updated TestMCDownloadForgeLaunch in the master branch(943d4b3dc8f494c8091b8caef1aa0eecc2607671), so forge launching should now work.
Before testing it, please use the official minecraftforge installer, as mclauncher-api doesn't support forge installing. If you had any additional questions, feel free to ask here :)

**Comment by mcNETDev** [comment]
I finally fixed the issue that i explained in the last post.
The tweaker class was set to FMLServerTweaker and not FMLTweaker.
Thanks for the awesome API.

Daniel | mcNETDev
