### ISSUE TITLE
[Question] Tos and Eula

### ISSUE THREAD

**Issue by Yunus1903** [tomsik68/mclauncher-api#16]
Does this API give me any problems with the Minecraft Terms of Service and the End User License Agreement?

**Comment by laci200270** [comment]
No

**Comment by tomsik68** [comment]
As long as your launcher doesn't give people without purchased account access to minecraft, everything should be all right. Mojang EULA and Terms of Service are not even cryptic, so you can read those for yourself in case you're interested in more details.

**Comment by Yunus1903** [comment]
Okay Thank You! :)
