### ISSUE TITLE
[Question] Video Tutorial

### ISSUE THREAD

**Issue by Yunus1903** [tomsik68/mclauncher-api#17]
Is there a video tutorial for this API?
I didn't understand every part in the Wiki and i would love to see a video that shows everything and some examples.

**Comment by tomsik68** [comment]
Currently, there's no video tutorial for this API. There's just this wiki and an example launcher (https://github.com/tomsik68/OneClickMC). If you want example code, OneClickMC is a good place to start. 

Video tutorial is an interesting idea. If you think it'd help you(and others) understand the API better, I'd start a tutorial series.

**Comment by Yunus1903** [comment]
Thank you for your reply, i would really love to see you doing a tutorial series on this really great API! :)

**Comment by laci200270** [comment]
@Yunus1903 also if you not understand the wiki you can look at this folder: https://github.com/tomsik68/mclauncher-api/tree/master/src/test/java there are some example at this place
