### ISSUE TITLE
API

### ISSUE THREAD

**Issue by JayDzz** [tomsik68/mclauncher-api#18]
Hey Guys!

Would it be possible to check if the username/password combination is right with this api?
With the previous api this was enough:
https://login.minecraft.net/?user=myemail@gmail.com&pass=mypassword&version=1.3

**Comment by tomsik68** [comment]
Yes, it's possible to check login credentials, but with the current version of this API, it's pretty complicated. It can be done by performing a password login like this:
```
// create profile based on credentials
LegacyProfile profile = new LegacyProfile(username, password);
// initialize login service
YDLoginService loginService = new YDLoginService();
// load the client token into login service. this method requires .minecraft folder as the only parameter
loginService.load(dotMinecraftFolder);
ISession session = null;
try{
    session = loginService.login(profile);
    // login success!
}catch(YDServiceAuthenticationException e){
    if(e.getCause() != null && e.getCause() instanceof LoginException){
        // incorrect credentials
    } else {
        // different error(network, JSON parsing etc)
    }
}
```

**Comment by JayDzz** [comment]
Hey, thanks for ur respond.
Is this possible to make in php?
Might want to be a nice project haha

**Comment by laci200270** [comment]
What do you think?Check the coorect udername-password pair?You need to make, and parse jsons.

**Comment by tomsik68** [comment]
@JayDzz It's definitely possible in PHP. You only need to know something about HTTP GET & POST requests and JSON parsing in PHP.
This page contains more information about structure of JSON login requests:  https://github.com/tomsik68/mclauncher-api/wiki/New-Minecraft-authentication-a.k.a.-Yggdrasil
