### ISSUE TITLE
[Not an issue] Output in jTextArea

### ISSUE THREAD

**Issue by ammarx** [tomsik68/mclauncher-api#20]
Hey,
I am sorry if this is the incorrect place for posting this.. But I really needed to ask..
Is there a way I can get the output shown on the console In a jTextArea?.. Example:

```
INFO: Updating asset file: minecraft/sounds/dig/cloth4.ogg (size:4844B)
Dec 24, 2015 3:04:42 AM sk.tomsik68.mclauncher.impl.versions.mcdownload.MCDResourcesInstaller downloadAssetList
INFO: Updating asset file: minecraft/sounds/mob/skeleton/hurt1.ogg (size:9986B)
Dec 24, 2015 3:04:42 AM sk.tomsik68.mclauncher.impl.versions.mcdownload.MCDResourcesInstaller downloadAssetList
INFO: Updating asset file: minecraft/sounds/dig/sand4.ogg (size:5491B)
```

This is the example you posted that I am using to download the files:

```
        final MCDownloadVersionList list = new MCDownloadVersionList();
        final MinecraftInstance mc = new MinecraftInstance(new File("testmc"));
        list.addObserver(new IObserver<String>() {
            private boolean installed = false;

            @Override
            public void onUpdate(IObservable<String> observable, String id) {
                id = (String) jComboBox1.getSelectedItem();
                
                IVersion changed = null;
                try {
                    changed = list.retrieveVersionInfo(id);
                    
                } catch (Exception e) {
                    e.printStackTrace();
                }
                System.out.println("Version "+changed.getId());
                if(installed) return;
                installed = true;
                System.out.println("Installing " + changed.getDisplayName());
                try {
                    changed.getInstaller().install(changed, mc, null);
                } catch (Exception e) {
                    e.printStackTrace();
                    //fail();
                }
            }
        });
        try {
          
            list.startDownload();
          
        } catch (Exception e) {
            e.printStackTrace();
            //fail();

        } 
```

something like this:

![screenshot from 2015-12-24 03 23 12](https://cloud.githubusercontent.com/assets/4668212/11986121/bf9819ce-a9ed-11e5-8810-45749a28d8b8.png)

**Comment by tomsik68** [comment]
MCLauncherAPI writes these text messages to a java.util.Logger. 
The logger is accessible via a static field: `sk.tomsik68.mclauncher.api.common.MCLauncherAPI.log`. In order to get these messages into a visual component, you need to create your own LogHandler that appends text from LogRecord to the text area.

**Comment by ammarx** [comment]
Thanks! :D Thats exactly what I wanted!

Btw are mods and inheritance supported in this API?

**Comment by tomsik68** [comment]
Inheritance is supported and I was able to launch minecraftforge with this API, so yes :smile:

**Comment by ammarx** [comment]
Um, is there a way I can get the default location of .minecraft folder?
I mean.. the current examples that are uploaded, create a new instance "testmc" and then download everything over there...

In windows example, the default location is:
%appdata%/.minecraft

In ubuntu:
home/.minecraft

Is there a way to get them using the API?

**Comment by ammarx** [comment]
Thanks for the help again :+1:
