### ISSUE TITLE
Help with forge (Using demo)

### ISSUE THREAD

**Issue by minecraftlog21** [tomsik68/mclauncher-api#22]
I tried using the provided demo and I keep getting problems with getting forge working.
====== FILE ======
import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;

import mistMinecraft.MinecraftPreload;
import sk.tomsik68.mclauncher.api.common.ILaunchSettings;
import sk.tomsik68.mclauncher.api.common.MCLauncherAPI;
import sk.tomsik68.mclauncher.api.common.mc.MinecraftInstance;
import sk.tomsik68.mclauncher.api.login.ISession;
import sk.tomsik68.mclauncher.api.versions.IVersion;
import sk.tomsik68.mclauncher.backend.GlobalAuthenticationSystem;
import sk.tomsik68.mclauncher.impl.common.Platform;
import sk.tomsik68.mclauncher.impl.versions.mcdownload.MCDownloadVersionList;

public class FORDGETEST {
	
	public static void main(String[] a) throws Exception {
		test();
	}
	
    public static void test() {
        MCLauncherAPI.log.setLevel(Level.ALL);
        try {
            // finally use my minecraft credentials
            System.out.println("Logging in...");

            final ISession session = GlobalAuthenticationSystem.login(null);
            System.out.println("Success! Launching...");
            final MinecraftInstance mc = new MinecraftInstance(
                    Platform.getCurrentPlatform().getWorkingDirectory());
            final MCDownloadVersionList versionList = new MCDownloadVersionList();
            IVersion toLaunch = versionList.retrieveVersionInfo("Pack2");
            System.out.println(toLaunch);
            try {
                toLaunch.getInstaller().install(toLaunch, mc, null);
                List<String> launchCommand = toLaunch.getLauncher()
                        .getLaunchCommand(session, mc, null,
                                toLaunch, new ILaunchSettings() {

                                    @Override
                                    public boolean isModifyAppletOptions() {
                                        return false;
                                    }

                                    @Override
                                    public File getJavaLocation() {
                                        return null;
                                    }

                                    @Override
                                    public List<String> getJavaArguments() {
                                        return Arrays
                                                .asList("-XX:+UseConcMarkSweepGC",
                                                        "-XX:+CMSIncrementalMode",
                                                        "-XX:-UseAdaptiveSizePolicy",
                                                        "-Xmn128M");
                                    }

                                    @Override
                                    public String getInitHeap() {
                                        return "512M";
                                    }

                                    @Override
                                    public String getHeap() {
                                        return "1G";
                                    }

                                    @Override
                                    public Map<String, String> getCustomParameters() {
                                        return null;
                                    }

                                    @Override
                                    public List<String> getCommandPrefix() {
                                        return null;
                                    }
                                }, null);
                for (String cmd : launchCommand) {
                    System.out.print(cmd + " ");
                }
                System.out.println();
                ProcessBuilder pb = new ProcessBuilder(
                        launchCommand);
                pb.redirectError(new File("mcerr.log"));
                pb.redirectOutput(new File("mcout.log"));
                pb.directory(mc.getLocation());
                Process proc = pb.start();
                BufferedReader br = new BufferedReader(
                        new InputStreamReader(proc.getInputStream()));
                String line;
                while (isProcessAlive(proc)) {
                    line = br.readLine();
                    if (line != null && line.length() > 0)
                        System.out.println(line);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            //versionList.startDownload();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    protected static boolean isProcessAlive(Process proc) {
        try {
            System.out.println("Process exited with error code:"
                    + proc.exitValue());
            return false;
        } catch (Exception e) {
            return true;
        }

    }

}

====== OUTPUT ======
Logging in...
Success! Launching...
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/Minecraft.Download/versions/Pack2/Pack2.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sk.tomsik68.mclauncher.util.HttpUtils.httpGet(HttpUtils.java:29)
	at sk.tomsik68.mclauncher.impl.versions.mcdownload.MCDownloadVersionList.retrieveVersionInfo(MCDownloadVersionList.java:43)
	at FORDGETEST.test(FORDGETEST.java:37)
	at FORDGETEST.main(FORDGETEST.java:22)

**Comment by tomsik68** [comment]
You need to have `Pack2/Pack2.json` in your `.minecraft/versions` folder. This looks like you don't have it in `.minecraft/versions` or you're using outdated mclauncher-api. Your `Pack2.json` should be in the same format as forge's JSON file(or any other version, but forge is a great example because it doesn't use its own jar).

**Comment by minecraftlog21** [comment]
I have checked the file are in place & works when I use the regular minecraft launcher,
This is the directory tree taken from the versions folder.
```
+---1.7.10
¦	¦	1.7.10.jar
¦	¦	1.7.10.json
¦	¦
¦	+---natives
¦			  avutil-ttv-51.dll
¦			  jinput-dx8.dll
¦			  jinput-dx8_64.dll
¦			  jinput-raw.dll
¦			  jinput-raw_64.dll
¦			  jinput-wintab.dll
¦			  libmfxsw64.dll
¦			  libmp3lame-ttv.dll
¦			  lwjgl.dll
¦			  lwjgl64.dll
¦			  OpenAL32.dll
¦			  OpenAL64.dll
¦			  swresample-ttv-0.dll
¦			  twitchsdk.dll
¦
+---1.7.10-Forge10.13.4.1614-1.7.10
¦		 1.7.10-Forge10.13.4.1614-1.7.10.json
¦
+---Forge1.7.10
¦		 Forge1.7.10.jar
¦		 Forge1.7.10.json
¦
+---Pack_2
		  Pack_2 - Copy.json
		  Pack_2.jar
		  Pack_2.json

```
The Contents of the Json file ('Pack_2.json').
```
{
  "id": "Pack_2",
  "time": "2015-06-10T02:10:34-0400",
  "releaseTime": "1960-01-01T00:00:00-0700",
  "type": "release",
  "minecraftArguments": "--username ${auth_player_name} --version ${version_name} --gameDir ${game_directory} --assetsDir ${assets_root} --assetIndex ${assets_index_name} --uuid ${auth_uuid} --accessToken ${auth_access_token} --userProperties ${user_properties} --userType ${user_type} --tweakClass cpw.mods.fml.common.launcher.FMLTweaker",
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "minimumLauncherVersion": 14.0,
  "assets": "1.7.10",
  "inheritsFrom": "1.7.10",
  "jar": "1.7.10",
  "libraries": [
    {
      "name": "net.minecraftforge:forge:1.7.10-10.13.4.1448-1.7.10",
      "url": "http://files.minecraftforge.net/maven/"
    },
    {
      "name": "net.minecraft:launchwrapper:1.11",
      "serverreq": true
    },
    {
      "name": "org.ow2.asm:asm-all:5.0.3",
      "serverreq": true
    },
    {
      "name": "com.typesafe.akka:akka-actor_2.11:2.3.3",
      "url": "http://files.minecraftforge.net/maven/",
      "checksums": [
        "ed62e9fc709ca0f2ff1a3220daa8b70a2870078e",
        "25a86ccfdb6f6dfe08971f4825d0a01be83a6f2e"
      ],
      "serverreq": true,
      "clientreq": true
    },
    {
      "name": "com.typesafe:config:1.2.1",
      "url": "http://files.minecraftforge.net/maven/",
      "checksums": [
        "f771f71fdae3df231bcd54d5ca2d57f0bf93f467",
        "7d7bc36df0989d72f2d5d057309675777acc528b"
      ],
      "serverreq": true,
      "clientreq": true
    },
    {
      "name": "org.scala-lang:scala-actors-migration_2.11:1.1.0",
      "url": "http://files.minecraftforge.net/maven/",
      "checksums": [
        "dfa8bc42b181d5b9f1a5dd147f8ae308b893eb6f",
        "8c9aaeeb68487ca519411a14068e1b4d69739207"
      ],
      "serverreq": true,
      "clientreq": true
    },
    {
      "name": "org.scala-lang:scala-compiler:2.11.1",
      "url": "http://files.minecraftforge.net/maven/",
      "checksums": [
        "56ea2e6c025e0821f28d73ca271218b8dd04926a",
        "1444992390544ba3780867a13ff696a89d7d1639"
      ],
      "serverreq": true,
      "clientreq": true
    },
    {
      "name": "org.scala-lang.plugins:scala-continuations-library_2.11:1.0.2",
      "url": "http://files.minecraftforge.net/maven/",
      "checksums": [
        "87213338cd5a153a7712cb574c0ddd2edfee0386",
        "0b4c1bf8d48993f138d6e10c0c144e50acfff581"
      ],
      "serverreq": true,
      "clientreq": true
    },
    {
      "name": "org.scala-lang.plugins:scala-continuations-plugin_2.11.1:1.0.2",
      "url": "http://files.minecraftforge.net/maven/",
      "checksums": [
        "1f7371605d4ba42aa26d3443440c0083c587b4e9",
        "1ea655dda4504ae0a367327e2340cd3beaee6c73"
      ],
      "serverreq": true,
      "clientreq": true
    },
    {
      "name": "org.scala-lang:scala-library:2.11.1",
      "url": "http://files.minecraftforge.net/maven/",
      "checksums": [
        "0e11da23da3eabab9f4777b9220e60d44c1aab6a",
        "1e4df76e835201c6eabd43adca89ab11f225f134"
      ],
      "serverreq": true,
      "clientreq": true
    },
    {
      "name": "org.scala-lang:scala-parser-combinators_2.11:1.0.1",
      "url": "http://files.minecraftforge.net/maven/",
      "checksums": [
        "f05d7345bf5a58924f2837c6c1f4d73a938e1ff0",
        "a1cbbcbde1dcc614f4253ed1aa0b320bc78d8f1d"
      ],
      "serverreq": true,
      "clientreq": true
    },
    {
      "name": "org.scala-lang:scala-reflect:2.11.1",
      "url": "http://files.minecraftforge.net/maven/",
      "checksums": [
        "6580347e61cc7f8e802941e7fde40fa83b8badeb",
        "91ce0f0be20f4a536321724b4b3bbc6530ddcd88"
      ],
      "serverreq": true,
      "clientreq": true
    },
    {
      "name": "org.scala-lang:scala-swing_2.11:1.0.1",
      "url": "http://files.minecraftforge.net/maven/",
      "checksums": [
        "b1cdd92bd47b1e1837139c1c53020e86bb9112ae",
        "d77152691dcf5bbdb00529af37aa7d3d887b3e63"
      ],
      "serverreq": true,
      "clientreq": true
    },
    {
      "name": "org.scala-lang:scala-xml_2.11:1.0.2",
      "url": "http://files.minecraftforge.net/maven/",
      "checksums": [
        "7a80ec00aec122fba7cd4e0d4cdd87ff7e4cb6d0",
        "62736b01689d56b6d09a0164b7ef9da2b0b9633d"
      ],
      "serverreq": true,
      "clientreq": true
    },
    {
      "name": "lzma:lzma:0.0.1",
      "serverreq": true
    },
    {
      "name": "net.sf.jopt-simple:jopt-simple:4.5",
      "serverreq": true
    },
    {
      "name": "com.google.guava:guava:17.0",
      "serverreq": true
    },
    {
      "name": "org.apache.commons:commons-lang3:3.3.2",
      "serverreq": true
    }
  ]
}
```
One more thing I did change the pack or file name to 'Pack_2' from 'Pack2'

**Comment by tomsik68** [comment]
I see, all the files are really in place. I suspect that the problem might be `minimumLauncherVersion` being float(as it's being parsed as an Integer(here: https://github.com/tomsik68/mclauncher-api/blob/master/src/main/java/sk/tomsik68/mclauncher/impl/versions/mcdownload/MCDownloadVersion.java#L43)). Could you please re-try with `minimumLauncherVersion: 14` in the JSON file ?

**Comment by minecraftlog21** [comment]
I have changed the version number to 14 and still nothing
```
  "id": "Pack_2",
  "time": "2015-06-10T02:10:34-0400",
  "releaseTime": "1960-01-01T00:00:00-0700",
  "type": "release",
  "minecraftArguments": "--username ${auth_player_name} --version ${version_name} --gameDir ${game_directory} --assetsDir ${assets_root} --assetIndex ${assets_index_name} --uuid ${auth_uuid} --accessToken ${auth_access_token} --userProperties ${user_properties} --userType ${user_type} --tweakClass cpw.mods.fml.common.launcher.FMLTweaker",
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "minimumLauncherVersion": 14,
  "assets": "1.7.10",
  "inheritsFrom": "1.7.10",
  "jar": "1.7.10",
  "libraries": [
```

**Comment by tomsik68** [comment]
I spotted the problem - your code & also files are alright, but release 0.3.1 doesn't support forge. In order to use forge, you need to get the latest version from git.

**Comment by mcNETDev** [comment]
in your code the pack name is "Pack2" and in your folder structure is "Pack_2"!

**Comment by minecraftlog21** [comment]
mcNETDev thank you for pointing that out but stated that I renamed the folders, files and file content to Pack_2 from Pack2 In my 2nd comment.

**Comment by minecraftlog21** [comment]
It worked thank you!
