### ISSUE TITLE
s3.amazonaws.com-Minecraft.Download is outdated

### ISSUE THREAD

**Issue by kutschkem** [tomsik68/mclauncher-api#33]
https://github.com/tomsik68/mclauncher-api/wiki/s3.amazonaws.com-Minecraft.Download is outdated.
The versions.json from s3 contains this:

` "__comment": "This URL is being phased out! Please update your scripts to check https://launchermeta.mojang.com/mc/game/version_manifest.json instead. Thanks <3 --Dinnerbone"`

That means MCDownloadOnlineVersionList as well as this wiki page should be updated.

**Comment by tomsik68** [comment]
Thanks for letting me know! Is it just the URL or are there some changes to structure of JSON objects, too?

**Comment by kutschkem** [comment]
I didn't look to hard but the new one has links to json files for every version, and these json files contain the actual urls for stuff.

**Comment by Safranil** [comment]
Hi,

I implemented the change to use the new URL in the PR #35.

But it's not compatible with Minecraft 1.13 and upper (see #36).
