### ISSUE TITLE
MC 1.13 broken

### ISSUE THREAD

**Issue by kangarko** [tomsik68/mclauncher-api#37]
Hey,

thanks for the library. I am trying to setup a custom launcher to download all assets for MC 1.13 but keep getting stuck at this line:

java.io.IOException: Server returned HTTP response code: 403 for URL: https://s3.amazonaws.com/Minecraft.Download/indexes/1.13.1.json

that is executed from IVersion#getInstaller().install(changed, mc, null);

The data url seems to be changed, could you please update?

ďakujem :)

**Comment by Safranil** [comment]
Hi,

See #35 and #33 for the issue about invalid URL.

Minecraft 1.13 is not yet supported, the JSON file has broken change, see #36.

I will write a patch in next days but you can use Minecraft 1.12 to test your custom launcher and switch to 1.13 when the patch come up.

**Comment by kangarko** [comment]
Thank you I understand!
