### ISSUE TITLE
the solution of offline game, if u don't know how to do, just see this 

### ISSUE THREAD

**Issue by Mikesame** [tomsik68/mclauncher-api#43]
this launcher api is so great and thanks a lot :) 

this is a offline example，it's easy and it works ! :

if(launchOptions.getOnline_mode() == 1){
            iSession = GlobalAuthenticationSystem.doPasswordLogin(launchOptions.getUserName(),launchOptions.getPassword());
        }else{
            iSession = new ISession() {
                public String getUsername() {
                    return launchOptions.getUserName();
                }

                public String getSessionID() {
                    return UUID.randomUUID().toString();
                }

                public String getUUID() {
                    return UUID.randomUUID().toString();
                }

                public ESessionType getType() {
                    return ESessionType.MOJANG;
                }

                public List<Prop> getProperties() {
                    return null;
                }
            };
        }

**Comment by tomsik68** [comment]
Thanks for your contribution. As this is not an issue, I'm closing it for now. If you want, you can add it to the wiki.
