### ISSUE TITLE
How to use forge with api?

### ISSUE THREAD

**Issue by maciekkkkkkk** [tomsik68/mclauncher-api#48]
I'm trying to run forge with code
```
        MinecraftInstance mc = new MinecraftInstance(Platform.getCurrentPlatform().getWorkingDirectory());

        ISession session = GlobalAuthenticationSystem.login(null);

        MCDownloadVersionList versionList = new MCDownloadVersionList(mc);
        IVersion toLaunch = versionList.retrieveVersionInfo("1.12.2-forge1.12.2-14.23.5.2838");
        toLaunch.getInstaller().install(toLaunch, mc, null);
```
but i've got error

```
Exception in thread "main" java.lang.NullPointerException
	at sk.tomsik68.mclauncher.impl.versions.mcdownload.MCDownloadVersion.fromJson(MCDownloadVersion.java:69)
	at sk.tomsik68.mclauncher.impl.versions.mcdownload.MCDownloadLocalVersionList.retrieveVersionInfo(MCDownloadLocalVersionList.java:58)
	at sk.tomsik68.mclauncher.impl.versions.mcdownload.MCDownloadVersionList.retrieveVersionInfo(MCDownloadVersionList.java:42)
	at com.followtm.btlauncher.Main.main(Main.java:36)
```
(line 36 in Main.java is `IVersion toLaunch = versionList.retrieveVersionInfo("1.12.2-forge1.12.2-14.23.5.2838");`

I installed forge by forge installer

**Comment by tomsik68** [comment]
I believe this is the same issue as #47 . Could you, please, try with the newest version of the API?

**Comment by FollowTM** [comment]
I'm using version 0.3.3

**Comment by tomsik68** [comment]
Ok then, thanks for the report, I'll look into it.

**Comment by tomsik68** [comment]
Could you, please, attach JSON file for that version? I suspect it doesn't contain information about asset index which is required right now. So I need to look how to find what assets to use with that version.

**Comment by FollowTM** [comment]
https://hastebin.com/okabaragaw.json

**Comment by maciekkkkkkk** [comment]
and? have you noticed the bug?

**Comment by tomsik68** [comment]
Yes, it's the case with the asset index. I'm currently testing OneClickMC with the Forge version you sent and it seems there are more things I broke when I introduced compatibility with new versions of Minecraft Launcher for Minecraft 1.13 . Mainly things around parsing libraries from JSON.

**Comment by maciekkkkkkk** [comment]
so can you fix it?

**Comment by tomsik68** [comment]
Yes, but it'll take a while. Sorry, I'm not able to fix it immediately.

**Comment by tomsik68** [comment]
The fix should be live, please update your version to 0.3.4. Thanks again for reporting and your patience!
