### ISSUE TITLE
URL to version.json

### ISSUE THREAD

**Issue by JakobDev** [tomsik68/mclauncher-api#49]
I use your Wiki to code my own Minecraft Launcher, but I got a problem: I need to download the version.json file, but the URL you provided [in the wiki](https://github.com/tomsik68/mclauncher-api/wiki/Extended-version-information) only works for older versions. If I try this URl with the latest Version (https://s3.amazonaws.com/Minecraft.Download/versions/1.14.3/1.14.3.json) it soes not work. Can you help me?

**Comment by tomsik68** [comment]
Hi, I'm sorry but some parts of the wiki are out of date right now. The way it works in the newest versions is, that `versions.json` is at https://launchermeta.mojang.com/mc/game/version_manifest.json . And URLs to individual version JSON files need to be extracted from that version manifest.

**Comment by JakobDev** [comment]
Thanks
