### ISSUE TITLE
Commandline Programm

### ISSUE THREAD

**Issue by JakobDev** [tomsik68/mclauncher-api#53]
While working my launcher in python, I#M be thinking it would be nice to have a command line program that can be used from every programming language and not only from Java.

I'm thinking at something like this:
`java -jar mclauncher-cmd install "release 1.14.3" "/home/Username/.minecraft"`
would install Minecraft 1.14.3 into "/home/Username/.minecraft. The Program print it's progress in the terminal.

`java -jar mclauncher-cmd command "release 1.14.3" "/home/Username/.minecraft"`
would print the command to run Minecraft. The Launcher just had to insert Username UUID, Seesion ID and other options and than execute the command.

**Comment by tomsik68** [comment]
Yes, like a headless minecraft launcher. Someone can totally make it happen using the api :smile:

**Comment by JakobDev** [comment]
Can you make the headless launcher? I have no experience in Java.

**Comment by tomsik68** [comment]
No, I currently have no plans to make a headless launcher. However, if you want, you can check out https://github.com/tomsik68/OneClickMC which requires minimum user interaction. It is a launcher I created to test the API with.

**Comment by JakobDev** [comment]
I tried to copy the code from the one click mc starter to use it, because it's easy to read even with less Java Experience, but this little example code doesn't works:
```
package jakobdev.mclauncher_cmd;

import sk.tomsik68.mclauncher.backend.MinecraftLauncherBackend;
import sk.tomsik68.mclauncher.impl.common.Platform;
import sk.tomsik68.mclauncher.api.versions.LatestVersionInformation;

public class mclauncher_cmd {
    public static void main(String[] args) throws Exception {
        MinecraftLauncherBackend minecraftLauncherBackend = new MinecraftLauncherBackend(Platform.getCurrentPlatform().getWorkingDirectory());
        LatestVersionInformation latest = minecraftLauncherBackend.getLatestVersionInformation();
        String lastVersion = latest.getLatestRelease();
        System.out.println(lastVersion);
    }
}
```
Error:
```
/usr/lib/jvm/java-8-openjdk-amd64/bin/java -javaagent:/snap/intellij-idea-community/152/lib/idea_rt.jar=36614:/snap/intellij-idea-community/152/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/icedtea-sound.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/management-agent.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/home/jakob/zw/mclauncher-cmd/out/production/mclauncher-cmd:/home/jakob/Downloads/mclauncher-api-0.3.4.jar jakobdev.mclauncher_cmd.mclauncher_cmd
Exception in thread "main" java.lang.NoClassDefFoundError: net/minidev/json/JSONValue
	at sk.tomsik68.mclauncher.impl.versions.mcdownload.MCDownloadOnlineVersionList.getLatestVersionInformation(MCDownloadOnlineVersionList.java:57)
	at sk.tomsik68.mclauncher.impl.versions.mcdownload.MCDownloadVersionList.getLatestVersionInformation(MCDownloadVersionList.java:53)
	at sk.tomsik68.mclauncher.backend.MinecraftLauncherBackend.getLatestVersionInformation(MinecraftLauncherBackend.java:34)
	at jakobdev.mclauncher_cmd.mclauncher_cmd.main(mclauncher_cmd.java:10)
Caused by: java.lang.ClassNotFoundException: net.minidev.json.JSONValue
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more

Process finished with exit code 1
```

**Comment by tomsik68** [comment]
mclauncher-api needs `json-smart` library to parse json. You need to somehow add it during build or specify where java can find it while launching.

**Comment by JakobDev** [comment]
I've downloaded json-smart 2.0 rc3 from [http://www.java2s.com/Code/Jar/j/Downloadjsonsmart20rc3jar.htm](herel) and added it to IntelliJ, but I still get the error.

**Comment by tomsik68** [comment]
Please download version 1.1.1 instead

**Comment by JakobDev** [comment]
It works now! Does your API has a function that just return the command without login in or something else? My launcher has a own profile system, so it would be great, if I get a String who I just have to replace Username, accesToken and something else and run it.

**Comment by tomsik68** [comment]
Not like that, there is one that starts building the process for you and stores the command internally. However, that needs an `ISession` object.
It is `MinecraftLauncherBackend::launchMinecraft`:
https://github.com/tomsik68/mclauncher-api/blob/07e3ce3731132f68ed7ce1aed216a5657d9e7411/src/main/java/sk/tomsik68/mclauncher/backend/MinecraftLauncherBackend.java#L72

**Comment by JakobDev** [comment]
Here is a picture of the profile editor of my new launcher:
![Screenshot at 2019-07-15 21:37:47](https://user-images.githubusercontent.com/15185051/61243809-10557d00-a749-11e9-9e9b-60d7f3aea0ff.png)
Is it possible to set all the settings from the picture on the launch command and capture the output for displaying in the launcher?

**Comment by tomsik68** [comment]
+ game directory: yes
+ resolution: only manually
+ executable: yes
+ JVM arguments: yes

Just use the other variant of `launchMinecraft` that allows you to pass `ILaunchSettings`
 https://github.com/tomsik68/mclauncher-api/blob/07e3ce3731132f68ed7ce1aed216a5657d9e7411/src/main/java/sk/tomsik68/mclauncher/backend/MinecraftLauncherBackend.java#L86

You can find more info about ILaunchSettings in the documentation here:
https://github.com/tomsik68/mclauncher-api/blob/07e3ce3731132f68ed7ce1aed216a5657d9e7411/src/main/java/sk/tomsik68/mclauncher/api/common/ILaunchSettings.java#L12

The rest of the settings is something that you should take care of yourself in your launcher. API doesn't provide any way to do that and it doesn't make sense for the API to provide it either.

**Comment by JakobDev** [comment]
I need now to Overide ISession to give my Username and my UUID to the game. But what should getSeesionID(), getType(), getProperties() return?

**Comment by tomsik68** [comment]
I'm sorry, I'm not sure what are the requirements there. I usually just get my ISession from logging in, so you're on your own with this.

**Comment by JakobDev** [comment]
I have now a working version that launches Minecraft! But I have a problem: If I use something like 1.14.3 or 1.12.1 as VersionId, it works great but if I use something like 1.12.2-forge1.12.2-14.23.3.2678 as VersionID, which is on my Computer, it crashed.

**Comment by tomsik68** [comment]
I tested forge quite recently with OneClickMC and it used to work. Could you open another issue and attach the stack trace?

**Comment by tomsik68** [comment]
I'm closing the issue now. Please open another one if you need help or join the gitter room to chat in real-time which might be better if you have a general question like this one :smile:
