### ISSUE TITLE
Python Library aviable

### ISSUE THREAD

**Issue by JakobDev** [tomsik68/mclauncher-api#58]
I jsut wnt to inform you, that I have taken a look at this again and I have now finished a Python Library based on your documentation. You can find it [here](https://pypi.org/project/minecraft-launcher-lib/
). It is currently a Beta who has some Problems with olderversions, but the newest Version and the newest Forge Version are working. [jdMinecraftLauncher](https://pypi.org/project/jdMinecraftLauncher/) is a program from me which are already using this new lib.

It would be nice, if you can add a link to my lib in your Readme or Wiki for People who are want to make a launcher and finding your Project.

**Comment by tomsik68** [comment]
Awesome, thanks for letting me know. I added your launcher to launchers list page along with a link to your library.
