### ISSUE TITLE
API to make custom launchers on 1.15.2

### ISSUE THREAD

**Issue by BarryV94** [tomsik68/mclauncher-api#59]
Does it work for minecraft 1.15.2 ? and does it download 1.15.2 forge if you want ? i was trying to make this work on my launcher but i couldn't :/ previously i was using jMCLaunchLib but now it is no longer updated and i need to find good launch lib which work well 
sorry for my english :)

**Comment by tomsik68** [comment]
I didn't test this library for a long time now, so I don't know. However, you can easily test it yourself by compiling and running OneClickMC: https://github.com/tomsik68/OneClickMC.

Sidenote: I'm not planning to update this library or implement new features, so I don't think this is the best choice if you're just starting a new project. But if you need quick help with something, you're welcome to ask in Gitter channel. I usually get on and respond to new messages.
