### ISSUE TITLE
Support for setting your skin

### ISSUE THREAD

**Issue by marcelroed** [tomsik68/mclauncher-api#69]
Hi! This project would be immensely useful to me if there was an API for setting your skin. Do you know if this is possible, @tomsik68 ?

Thanks!

**Comment by tomsik68** [comment]
Hi Marcel! I believe there is one. It isn't exposed by mclauncher-api at the moment, but I'm sure you can easily find it in the java edition launcher.

**Comment by marcelroed** [comment]
Hi Tomas! Thanks for the reply. I found what I was looking for on www.wiki.vg. I'll close the issue since I don't think it needs to be added to the repo.
