### ISSUE TITLE
Yggdrassil -> Yggdrasil

### ISSUE THREAD

**Issue by not-ivy** [tomsik68/mclauncher-api#70]
Typo found here:
https://github.com/tomsik68/mclauncher-api/wiki#what-can-it-do-right-now

**Comment by tomsik68** [comment]
Thanks for reporting this! I fixed the typo on that page :tada:
https://github.com/tomsik68/mclauncher-api/wiki/Home/_compare/92f3305c8ccee2b7278d3d21b86d4026ef7ea5dd...549486038899f139bf4a52cb3142dccf401b155e
