### ISSUE TITLE
Migrate to https

### ISSUE THREAD

**Issue by henrik42** [tomsik68/mclauncher-api#76]
Any chance to merge https://github.com/LionZXY/mclauncher-api/commit/37e0f29fc701ab77dfe67d615979bcc132369958 ? 
Download via HTTP doesn't work anymore it seems.

**Comment by tomsik68** [comment]
Hey, I cherry-picked the commit that you mentioned and released a new version into the maven repo. Let me know if it works any better.

**Comment by henrik42** [comment]
Hi, sorry for the late response and thanks for your help. I must admit, I don't know how to comsume your release. Should I use a deps.edn :mvn ot :git dependency? I can't even tell what version your release has. Can I browse your release repo somehow?
Sorry for my incompetence. I'm trying to use your new release for https://github.com/lambdaisland/witchcraft-workshop/blob/main/deps.edn which uses sk.tomsik68/mclauncher-api {:mvn/version "0.3.6"} at the moment. 
Do you have any hint for me how to proceed?

**Comment by tomsik68** [comment]
Sorry for the lack of clarity! Can you try consuming mclauncher-api 0.3.7 from my maven repo? You can find guides in the [repo's readme](https://github.com/tomsik68/maven-repo#quick-start). 

Based on your edn file, it seems like you just need to bump to "0.3.7".

**Comment by henrik42** [comment]
Great! Works like a charm. Thank's a lot.
You may update the readme with an example for deps.edn:

```
{:deps {sk.tomsik68/mclauncher-api {:mvn/version "0.3.7"}}
 :mvn/repos {"sk_tomsik68" {:url "https://raw.githubusercontent.com/tomsik68/maven-repo/master/"}}}
```
