### ISSUE TITLE
Could you make forge injection?

### ISSUE THREAD

**Issue by laci200270** [tomsik68/mclauncher-api#9]
I think the modpack.jar injecting to main jar...

**Comment by tomsik68** [comment]
I've looked into Forge injection without damaging the JAR file(which is probably what you want) and it looks like it shouldn't be too hard. So the answer is yes! I'll add that :)

**Comment by laci200270** [comment]
Yes,I think that.
Thanks! :)

**Comment by laci200270** [comment]
When possible to add this feature? :)

**Comment by laci200270** [comment]
Sorry I found that.. :)
